FROM apache/airflow:2.10.5

# Copia o arquivo de dependências do projeto
COPY requirements.txt /requirements.txt

# Instala as dependências adicionais (as mesmas do pipeline)
RUN pip install --no-cache-dir -r /requirements.txt